main: space.gorogoro.creativecommands.CreativeCommands
name: CreativeCommands
version: 1.1
api-version: 1.15
description: クリエマップ用プラグイン
author: kubotan
website: https://gorogoro.space/

commands:
  selfgive:
    description: 自分にgiveします
    usage: §c/<command> (item id) (amount)§7- 自分にgiveします
  headgive:
    description: 自分に指定したプレイヤーの頭をgiveします
    usage: §c/<command> (player name) (amount)§7- 自分に指定したプレイヤーの頭をgiveします
    